---
- name: "configure_neofetch_for_user | Create home directories for neofetch config for all current users"
  when: user != 'lost+found' and home_directories.stdout_lines
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/neofetch"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    recurse: yes
    mode: "0755"

- name: "configure_neofetch_for_user | Copy neofetch configuration to home directories for all current users"
  ansible.builtin.copy:
    src: "files/neofetch.conf"
    dest: "/home/{{ user }}/.config/neofetch/config.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: "configure_neofetch_for_user | Enable Neofetch for all current users"
  when: user != 'lost+found'
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: "neofetch"
    state: present
