---
- name: "enable_byobu_for_user | Enable Byobu for user: {{ user }}"
  become_user: "{{ user }}"
  become: true
  block:
    - name: "enable_byobu_for_user | Enable Byobu"
      changed_when: false
      ignore_errors: true
      ansible.builtin.command: "byobu-enable"

    - name: "enable_byobu_for_user | Import the byobu backend for user: {{ user }}"
      ansible.builtin.template:
        src: "templates/backend.j2"
        dest: "/home/{{ user }}/.byobu/backend"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"

    - name: "enable_byobu_for_user | Enable byobu prompt for user: {{ user }}"
      register: output
      changed_when: false
      failed_when: false
      ignore_errors: true
      ansible.builtin.command: "byobu-enable-prompt"

