---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_byobu"
      tags:
        - "labocbz.install_byobu"
      vars:
        install_byobu__install_neofetch: "{{ inv_install_byobu__install_neofetch }}"
        install_byobu__enable_neofetch_for_all: "{{ inv_install_byobu__enable_neofetch_for_all }}"
        install_byobu__log_commands_for_all: "{{ inv_install_byobu__log_commands_for_all }}"
        install_byobu__set_nano_as_default_for_all: "{{ inv_install_byobu__set_nano_as_default_for_all }}"
      ansible.builtin.include_role:
        name: "labocbz.install_byobu"
