---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-debian-11"
  gather_facts: false
  tasks:

    - name: "Get list of directories in /home"
      when: inv_install_byobu__enable_neofetch_for_all | default(false)
      register: home_directories
      changed_when: home_directories.rc != 0
      ansible.builtin.command: |
        ls /home

    - name: "Check Neofetch installs"
      when: inv_install_byobu__install_neofetch | default(false)
      block:
        - name: "Check Neofetch for root"
          block:
            - name: "Check Neofetch command response"
              register: output
              changed_when: output.rc != 0
              failed_when: output.rc != 0
              ansible.builtin.command: "neofetch"

            - name: "Check Neofetch install and configuration for root"
              register: file_check
              failed_when: not file_check.stat.exists
              ansible.builtin.stat:
                path: "/root/.config/neofetch/config.conf"

        - name: "Check Neofetch for all users"
          when: inv_install_byobu__enable_neofetch_for_all and home_directories
          block:
            - name: "Check Neofetch command response for all users"
              loop: "{{ home_directories.stdout_lines }}"
              loop_control:
                loop_var: "user"
              when: user != 'lost+found'
              become: true
              become_user: "{{ user }}"
              register: output
              changed_when: output.rc != 0
              failed_when: output.rc != 0
              ansible.builtin.command: "neofetch"

            - name: "Check Neofetch install and configuration for all users"
              loop: "{{ home_directories.stdout_lines }}"
              loop_control:
                loop_var: "user"
              when: user != 'lost+found'
              become: true
              become_user: "{{ user }}"
              register: file_check
              failed_when: not file_check.stat.exists
              ansible.builtin.stat:
                path: "/home/{{ user }}/.config/neofetch/config.conf"

    - name: "Check Byobu installs"
      block:
        - name: "Check Byobu command response for root"
          register: output
          changed_when: output.rc != 0
          failed_when: output.rc != 1
          ansible.builtin.command: "byobu"

        - name: "Check Byobu for all users"
          when: home_directories | default(false)
          block:
            - name: "Get Byobu command response for all users"
              loop: "{{ home_directories.stdout_lines }}"
              loop_control:
                loop_var: "user"
              when: user != 'lost+found'
              become: true
              become_user: "{{ user }}"
              register: output
              changed_when: output.rc != 0
              failed_when: output.rc != 1
              ansible.builtin.command: "byobu"
