---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_byobu"
      tags:
        - "labocbz.install_byobu"
      vars:
        install_byobu_install_neofetch: "{{ inv_install_byobu_install_neofetch }}"
        install_byobu_enable_neofetch_for_all: "{{ inv_install_byobu_enable_neofetch_for_all }}"
        install_byobu_enable_byobu_for_all: "{{ inv_install_byobu_enable_byobu_for_all }}"
      ansible.builtin.include_role:
        name: "labocbz.install_byobu"
